language: python
python:
  - "3.3"
env:
  - DJANGO=1.6 DJANGO_SETTINGS_MODULE=tests.settings
install:
  - pip install coveralls
  - pip install pep8
script:
  - coverage run --source=django_crucrudile -- setup.py test
after_success:
  - coverage report -m
  - pep8 django_crucrudile
  - coveralls
