language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
install:
  - pip install python-coveralls
  - pip install coverage
  - pip install Django==$DJANGO
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run --source=django_crucrudile runtests.py 
after_success:
  - coverage report -m
  - coveralls
