language: python
python:
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.6 DJANGO_SETTINGS_MODULE=tests.settings
cache:
  directories:
  - /home/travis/build/cache/
  - /home/travis/virtualenv/python3.4.0/lib/python3.4/site-packages
install:
  - pip install coverage coveralls pep8
  - pip install .
script:
  - nosetests
after_success:
  - pep8 django_crucrudile
  - coveralls
