language: python
python:
  - "3.3"
env:
  - DJANGO=1.6
install:
  - pip install coveralls
  - pip install pep8
  - pip install -r tests/requirements.txt
  - pip install .
script:
  - ./runtests.py
after_success:
  - pep8 django_crucrudile
  - coverage report -m
  - coveralls
