language: python
python:
  - "3.4"
env:
  - DJANGO=1.6 DJANGO_SETTINGS_MODULE=tests.settings
cache:
  directories:
    - /home/travis/build/cache/xg
    - /home/travis/virtualenv/python3.4.0/lib/python3.4/site-packages
install:
  - pip install coveralls
  - pip install pep8
before_script:
  - sh -c "[ -d /home/travis/build/cache/ ] || mkdir /home/travis/build/cache"
  - sh -c "cp /home/travis/build/cache/*.egg . -r || echo"
script:
  - coverage run --source=django_crucrudile -- setup.py test
after_script:
  - cp *.egg /home/travis/build/cache/ -r
after_success:
  - coverage report -m
  - pep8 django_crucrudile
  - coveralls
