language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
install:
  - pip install python-coveralls
  - pip install Django==$DJANGO
  - pip install -r requirements.txt
  - pip install .
script:
  - python setup.py test
after_success:
  - coveralls
