language: python
python:
  - "3.4"
env:
  - DJANGO=1.6 DJANGO_SETTINGS_MODULE=tests.settings
cache:
  directories:
    - /home/travis/virtualenv/python3.4/lib/python3.4/site-packages
install:
  - pip install coveralls
  - pip install pep8
script:
  - coverage run --source=django_crucrudile -- setup.py test
after_success:
  - coverage report -m
  - pep8 django_crucrudile
  - coveralls
